/** Explicit spellings only. Adding an alias changes matching in both documents. */
export const SKILL_ALIASES: Readonly<Record<string, readonly string[]>> = {
  react: ["react", "react.js", "reactjs"],
  nodejs: ["node", "node.js", "nodejs", "node js"],
  postgresql: ["postgresql", "postgres", "psql"],
  aws: ["aws", "amazon web services"],
  "rest api": ["rest api", "rest apis", "restful api", "restful apis", "rest-api", "rest-apis"],
  typescript: ["typescript", "type script"],
  javascript: ["javascript", "java script", "js"],
  python: ["python"],
  java: ["java"],
  "c++": ["c++", "cpp"],
  "c#": ["c#", "csharp", "c sharp"],
  // Bare "go" is too common in prose to treat as a programming language.
  go: ["golang", "go language", "go programming language"],
  rust: ["rust", "rustlang"],
  html: ["html", "html5"],
  css: ["css", "css3"],
  sql: ["sql", "structured query language"],
  mysql: ["mysql", "my sql"],
  sqlite: ["sqlite", "sqlite3"],
  mongodb: ["mongodb", "mongo db", "mongo"],
  redis: ["redis"],
  docker: ["docker"],
  kubernetes: ["kubernetes", "k8s"],
  git: ["git"],
  "github actions": ["github actions"],
  linux: ["linux"],
  azure: ["azure", "microsoft azure"],
  gcp: ["gcp", "google cloud", "google cloud platform"],
  graphql: ["graphql", "graph ql"],
  nextjs: ["next.js", "nextjs", "next js"],
  angular: ["angular"],
  vue: ["vue", "vue.js", "vuejs"],
  "react native": ["react native", "react-native"],
  express: ["express", "express.js", "expressjs"],
  django: ["django"],
  flask: ["flask"],
  "spring boot": ["spring boot", "springboot"],
  ".net": [".net", "dotnet", "dot net"],
  terraform: ["terraform"],
  "ci/cd": ["ci/cd", "ci / cd", "ci-cd", "continuous integration", "continuous delivery", "continuous deployment"],
  jest: ["jest"],
  playwright: ["playwright"],
  cybersecurity: ["cybersecurity", "cyber security", "cyber-security"],
  "application security": ["application security", "appsec", "app sec"],
  "infrastructure security": ["infrastructure security"],
  "owasp top 10": ["owasp top 10", "owasp top ten", "owasp top-10"],
  vulnerabilities: ["vulnerability", "vulnerabilities"],
  ctf: ["ctf", "ctfs", "capture the flag", "capture-the-flag"],
  networking: ["networking", "computer networking", "networking fundamentals", "network fundamentals"],
  http: ["http", "hypertext transfer protocol"],
  tls: ["tls", "transport layer security"],
  dns: ["dns", "domain name system"],
  devops: ["devops", "dev ops", "dev-ops"],
};
